name: 'Cargo Update'
description: 'Run cargo update and check for changes'

outputs:
  changed:
    description: 'Whether Cargo.lock was changed'
    value: ${{ steps.changes.outputs.changed }}

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Run cargo update
      shell: bash
      run: cargo update

    - name: Check for changes
      id: changes
      shell: bash
      run: |
        if git diff --quiet Cargo.lock; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
